"""
VISE OS Monitoring Module

Observability and alerting infrastructure for the VISE OS platform.
Provides Prometheus metrics, alert management, and analytics reporting.

Components:
- metrics: Prometheus metrics collection
- alerts: Alert system with escalation
- analytics: Reporting and analytics service
"""

from src.monitoring.alerts import (
    ALERT_CONFIGS,
    ESCALATION_TIMEOUTS,
    Alert,
    AlertCategory,
    AlertConfig,
    AlertError,
    AlertManager,
    AlertSeverity,
    AlertStatus,
    AutoRemediationEngine,
    EscalationError,
    OnCallPerson,
    OnCallRouter,
    OnCallSchedule,
    OnCallTier,
    RemediationAction,
    RemediationError,
    RemediationResult,
    alert_manager,
    clear_alert_manager_cache,
    get_alert_manager,
)
from src.monitoring.analytics import (
    REPORT_CONFIGS,
    AggregationPeriod,
    AnalyticsError,
    AnalyticsETLPipeline,
    DimAgency,
    DimCountry,
    DimDate,
    DimSite,
    DimTime,
    ETLError,
    ExportError,
    ExportFormat,
    FactBooking,
    FactDailyAgencyStats,
    FactDailySiteStats,
    FactHourlyQueueStats,
    ReportConfig,
    ReportExportService,
    ReportGenerationError,
    ReportGenerator,
    ReportScheduler,
    ReportType,
    get_export_service,
    get_report_generator,
    get_report_scheduler,
)
from src.monitoring.metrics import (
    REGISTRY,
    AccountMetrics,
    APIMetrics,
    BookingMetrics,
    BrowserMetrics,
    CaptchaMetrics,
    CreditMetrics,
    DirectusMetrics,
    PaymentMetrics,
    ProxyMetrics,
    QueueMetrics,
    metrics,
)

__all__ = [
    # Metrics
    "REGISTRY",
    "metrics",
    "BookingMetrics",
    "QueueMetrics",
    "BrowserMetrics",
    "ProxyMetrics",
    "CaptchaMetrics",
    "AccountMetrics",
    "PaymentMetrics",
    "APIMetrics",
    "DirectusMetrics",
    "CreditMetrics",
    # Alerts
    "AlertManager",
    "get_alert_manager",
    "clear_alert_manager_cache",
    "alert_manager",
    "AutoRemediationEngine",
    "OnCallRouter",
    "Alert",
    "AlertConfig",
    "OnCallPerson",
    "OnCallSchedule",
    "RemediationAction",
    "RemediationResult",
    "AlertSeverity",
    "AlertCategory",
    "AlertStatus",
    "OnCallTier",
    "ALERT_CONFIGS",
    "ESCALATION_TIMEOUTS",
    "AlertError",
    "EscalationError",
    "RemediationError",
    # Analytics
    "ReportGenerator",
    "AnalyticsETLPipeline",
    "ReportExportService",
    "ReportScheduler",
    "get_report_generator",
    "get_export_service",
    "get_report_scheduler",
    "DimAgency",
    "DimSite",
    "DimDate",
    "DimTime",
    "DimCountry",
    "FactBooking",
    "FactDailyAgencyStats",
    "FactDailySiteStats",
    "FactHourlyQueueStats",
    "ReportConfig",
    "REPORT_CONFIGS",
    "ReportType",
    "ExportFormat",
    "AggregationPeriod",
    "AnalyticsError",
    "ETLError",
    "ReportGenerationError",
    "ExportError",
]
